nodeLinker: node-modules

# Support multiple architectures - download pre-built binaries instead of compiling
supportedArchitectures:
  os: ["linux"]
  cpu: ["x64", "arm64"]
  libc: ["glibc"]

yarnPath: .yarn/releases/yarn-4.9.1.cjs
